// city,state,lat,lng,radius
export const coolList = [
    {
        'city': "Birmingham", 
        'state': "AL",
        'latitude': 33.5277,
        'longitude': -86.7987,
        'r': 15,
        'count': 0,
    },
    {
        'city': "Huntsville", 
        'state': "AL", 
        'latitude': 34.6988,
        'longitude': -86.6412,
        'r': 10,
        'count': 0,
    },
    {
        'city': "Little Rock",
        'state': "AR",
        'latitude': 34.7256,
        'longitude': -92.3576,
        'r': 10,
        'count': 0,
    },
    {
        'city': "Phoenix",
        'state': "AZ",
        'latitude': 33.5722,
        'longitude': -112.0891,
        'r': 25,
        'count': 0,
    },
    {
        'city': "Tucson",
        'state': "AZ",
        'latitude': 32.1545,
        'longitude': -110.8782,
        'r': 15,
        'count': 0,
    },
    {
        'city': "Bakersfield",
        'state': "CA",
        'latitude': 35.3529,
        'longitude': -119.0359,
        'r': 15,
        'count': 0,
    },
    {
        'city': "Fresno",
        'state': "CA",
        'latitude': 36.7831,
        'longitude': -119.7941,
        'r': 15,
        'count': 0,
    },
    {
        'city': "Los Angeles",
        'state': "CA",
        'latitude': 34.1139,
        'longitude': -118.4068,
        'r': 35,
        'count': 0,
    },
    {
        'city': "Sacramento",
        'state': "CA",
        'latitude': 38.5667,
        'longitude': -121.4683,
        'r': 15,
        'count': 0,
    },
    {
        'city': "San Diego",
        'state': "CA",
        'latitude': 32.8312,
        'longitude': -117.1225,
        'r': 15,
        'count': 0,
    },
    {
        'city': "San Francisco",
        'state': "CA",
        'latitude': 37.7562,
        'longitude': -122.443,
        'r': 20,
        'count': 0,
    },
    {
        'city': "San Jose",
        'state': "CA",
        'latitude': 37.3019,
        'longitude': -121.8486,
        'r': 20,
        'count': 0,
    },
    {
        'city': "Colorado Springs",
        'state': "CO",
        'latitude': 38.8674,
        'longitude': -104.7606,
        'r': 15,
        'count': 0,
    },
    {
        'city': "Denver",
        'state': "CO",
        'latitude': 39.7621,
        'longitude': -104.8759,
        'r': 25,
        'count': 0,
    },
    {
        'city': "Hartford",
        'state': "CT",
        'latitude': 41.7661,
        'longitude': -72.6834,
        'r': 10,
        'count': 0,
    },
    {
        'city': "New Haven",
        'state': "CT",
        'latitude': 41.3112,
        'longitude': -72.9246,
        'r': 15,
        'count': 0,
    },
    {
        'city': "Washington",
        'state': "DC",
        'latitude': 38.9047,
        'longitude': -77.0163,
        'r': 20,
        'count': 0,
    },
    {
        'city': "Jacksonville",
        'state': "FL",
        'latitude': 30.3322,
        'longitude': -81.6749,
        'r': 15,
        'count': 0,
    },
    {
        'city': "Miami",
        'state': "FL",
        'latitude': 25.7839,
        'longitude': -80.2102,
        'r': 25,
        'count': 0,
    },
    {
        'city': "Orlando",
        'state': "FL",
        'latitude': 28.4772,
        'longitude': -81.3369,
        'r': 15,
        'count': 0,
    },
    {
        'city': "Tampa",
        'state': "FL",
        'latitude': 27.9942,
        'longitude': -82.4451,
        'r': 25,
        'count': 0,
    },
    {
        'city': "Athens",
        'state': "GA",
        'latitude': 33.9508,
        'longitude': -83.3689,
        'r': 10,
        'count': 0,
    },
    {
        'city': "Atlanta",
        'state': "GA",
        'latitude': 33.7627,
        'longitude': -84.4224,
        'r': 25,
        'count': 0,
    },
    {
        'city': "Des Moines",
        'state': "IA",
        'latitude': 41.5725,
        'longitude': -93.6105,
        'r': 15,
        'count': 0,
    },
    {
        'city': "Chicago",
        'state': "IL",
        'latitude': 41.8373,
        'longitude': -87.6862,
        'r': 20,
        'count': 0,
    },
    {
        'city': "Indianapolis",
        'state': "IN",
        'latitude': 39.7771,
        'longitude': -86.1458,
        'r': 20,
        'count': 0,
    },
    {
        'city': "Kansas City",
        'state': "KS",
        'latitude': 39.1234,
        'longitude': -94.7443,
        'r': 20,
        'count': 0,
    },
    {
        'city': "St. Louis",
        'state': "MI",
        'latitude': 43.4082,
        'longitude': -84.6118,
        'r': 20,
        'count': 0,
    },
    {
        'city': "Lexington",
        'state': "KY",
        'latitude': 38.0423,
        'longitude': -84.4587,
        'r': 20,
        'count': 0,
    },
    {
        'city': "Louisville",
        'state': "KY",
        'latitude': 38.1663,
        'longitude': -85.6485,
        'r': 15,
        'count': 0,
    },
    {
        'city': "New Orleans",
        'state': "LA",
        'latitude': 30.0687,
        'longitude': -89.9288,
        'r': 40,
        'count': 0,
    },
    {
        'city': "Boston",
        'state': "MA",
        'latitude': 42.3188,
        'longitude': -71.0846,
        'r': 20,
        'count': 0,
    },
    {
        'city': "Baltimore",
        'state': "MD",
        'latitude': 39.3051,
        'longitude': -76.6144,
        'r': 15,
        'count': 0,
    },
    {
        'city': "Portland",
        'state': "ME",
        'latitude': 43.6773,
        'longitude': -70.2715,
        'r': 15,
        'count': 0,
    },
    {
        'city': "Ann Arbor",
        'state': "MI",
        'latitude': 42.2755,
        'longitude': -83.7312,
        'r': 10,
        'count': 0,
    },
    {
        'city': "Detroit",
        'state': "MI",
        'latitude': 42.3834,
        'longitude': -83.1024,
        'r': 20,
        'count': 0,
    },
    {
        'city': "Minneapolis",
        'state': "MN",
        'latitude': 44.9635,
        'longitude': -93.2678,
        'r': 20,
        'count': 0,
    },
    {
        'city': "St. Louis",
        'state': "MO",
        'latitude': 38.6358,
        'longitude': -90.2451,
        'r': 20,
        'count': 0,
    },
    {
        'city': "Jackson",
        'state': "MS",
        'latitude': 32.3163,
        'longitude': -90.2124,
        'r': 20,
        'count': 0,
    },
    {
        'city': "Charlotte",
        'state': "NC",
        'latitude': 35.208,
        'longitude': -80.8304,
        'r': 20,
        'count': 0,
    },
    {
        'city': "Raleigh",
        'state': "NC",
        'latitude': 35.8325,
        'longitude': -78.6435,
        'r': 20,
        'count': 0,
    },
    {
        'city': "Wilmington",
        'state': "NC",
        'latitude': 34.21,
        'longitude': -77.8866,
        'r': 20,
        'count': 0,
    },
    {
        'city': "Albuquerque",
        'state': "NM",
        'latitude': 35.1053,
        'longitude': -106.6464,
        'r': 15,
        'count': 0,
    },
    {
        'city': "Santa Fe",
        'state': "NM",
        'latitude': 35.6619,
        'longitude': -105.9819,
        'r': 15,
        'count': 0,
    },
    {
        'city': "New York",
        'state': "NY",
        'latitude': 40.6943,
        'longitude': -73.9249,
        'r': 20,
        'count': 0,
    },
    {
        'city': "Cincinnati",
        'state': "OH",
        'latitude': 39.1413,
        'longitude': -84.5061,
        'r': 20,
        'count': 0,
    },
    {
        'city': "Cleveland",
        'state': "OH",
        'latitude': 41.4767,
        'longitude': -81.6804,
        'r': 20,
        'count': 0,
    },
    {
        'city': "Columbus",
        'state': "OH",
        'latitude': 39.9862,
        'longitude': -82.985,
        'r': 20,
        'count': 0,
    },
    {
        'city': "Bend",
        'state': "OR",
        'latitude': 44.0562,
        'longitude': -121.3087,
        'r': 10,
        'count': 0,
    },
    {
        'city': "Eugene",
        'state': "OR",
        'latitude': 44.0563,
        'longitude': -123.1173,
        'r': 10,
        'count': 0,
    },
    {
        'city': "Portland",
        'state': "OR",
        'latitude': 45.5372,
        'longitude': -122.65,
        'r': 20,
        'count': 0,
    },
    {
        'city': "Philadelphia",
        'state': "PA",
        'latitude': 40.0077,
        'longitude': -75.1339,
        'r': 20,
        'count': 0,
    },
    {
        'city': "Pittsburgh",
        'state': "PA",
        'latitude': 40.4396,
        'longitude': -79.9762,
        'r': 15,
        'count': 0,
    },
    {
        'city': "San Juan",
        'state': "PR",
        'latitude': 18.4037,
        'longitude': -66.0636,
        'r': 15,
        'count': 0,
    },
    {
        'city': "Providence",
        'state': "RI",
        'latitude': 41.823,
        'longitude': -71.4187,
        'r': 15,
        'count': 0,
    },
    {
        'city': "Charleston",
        'state': "SC",
        'latitude': 32.8153,
        'longitude': -79.9628,
        'r': 15,
        'count': 0,
    },
    {
        'city': "Columbia",
        'state': "SC",
        'latitude': 34.0376,
        'longitude': -80.9037,
        'r': 15,
        'count': 0,
    },
    {
        'city': "Greenville",
        'state': "SC",
        'latitude': 34.8353,
        'longitude': -82.3647,
        'r': 10,
        'count': 0,
    },
    {
        'city': "Knoxville",
        'state': "TN",
        'latitude': 35.9692,
        'longitude': -83.9496,
        'r': 10,
        'count': 0,
    },
    {
        'city': "Memphis",
        'state': "TN",
        'latitude': 35.1046,
        'longitude': -89.9773,
        'r': 15,
        'count': 0,
    },
    {
        'city': "Nashville",
        'state': "TN",
        'latitude': 36.1715,
        'longitude': -86.7843,
        'r': 10,
        'count': 0,
    },
    {
        'city': "Austin",
        'state': "TX",
        'latitude': 30.3004,
        'longitude': -97.7522,
        'r': 15,
        'count': 0,
    },
    {
        'city': "Dallas",
        'state': "TX",
        'latitude': 32.7936,
        'longitude': -96.7662,
        'r': 40,
        'count': 0,
    },
    {
        'city': "Houston",
        'state': "TX",
        'latitude': 29.7863,
        'longitude': -95.3889,
        'r': 30,
        'count': 0,
    },
    {
        'city': "Salt Lake City",
        'state': "UT",
        'latitude': 40.7777,
        'longitude': -111.9306,
        'r': 25,
        'count': 0,
    },
    {
        'city': "Norfolk",
        'state': "VA",
        'latitude': 36.8945,
        'longitude': -76.259,
        'r': 25,
        'count': 0,
    },
    {
        'city': "Richmond",
        'state': "VA",
        'latitude': 37.5295,
        'longitude': -77.4756,
        'r': 20,
        'count': 0,
    },
    {
        'city': "Seattle",
        'state': "WA",
        'latitude': 47.6211,
        'longitude': -122.3244,
        'r': 30,
        'count': 0,
    },
    {
        'city': "Olympia",
        'state': "WA",
        'latitude': 47.0417,
        'longitude': -122.8959,
        'r': 15,
        'count': 0,
    }
];
